# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 743e2b94a97507b9e90b7d518965607717e69b28871befc89e887dd8e1fcaa9b3d5e35bd888f595dbfd8074c763de937bb5b544cd46830f01c5526bc7e2b6649

test:
  secret_key_base: a605661a0c51219df0a2cbf727768256f79e3ef9e9aae0d8cbfb38efd849f75ed55511658579d92458388d4b5dd803b8c9eb8e1aa483ccabd9080eacd5bd2497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
